# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Verse' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Verse
  pod 'Moya/RxSwift', '12.0.1'
  pod 'SnapKit', '4.2.0'
  pod 'RxCocoa', '4.5.0'

  target 'VerseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VerseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
